pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - check-success=WIP
      - "#approved-reviews-by>=1"
      - author!=dependabot[bot]
    actions:
      merge:
        method: merge