package co.anbora.labs.kse.ide.settings

enum class OptionType {

    CERT_TYPE, LOCK_STATUS, CERT_STATUS,
    ENTRY_NAME, KEY_SIZE, CERTIFICATE_EXPIRY,
    SKI, ISSUER_DN, ISSUER_CN, ISSUER_O,
    ALGORITHM, CURVE, LAST_MODIFIED,
    AKI, SUBJECT_DN, SUBJECT_CN, SUBJECT_O;

}